config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # devise_for :users
  devise_for :users, :controllers => {:registrations => "registrations"}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :plants do
    member do
      get 'new' => 'charges#new'
      post 'checkout_payment' => 'charges#checkout_payment'
    end
  end
  get 'welcome/about_us'
  get 'welcome/services'
  get 'welcome/blog'
  get 'welcome/contact_us'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :plants
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :category
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  serialize :address
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = %i[email name address password password_confirmation remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :get_plant, only: [:new, :checkout_payment]

  def new; end

  def checkout_payment
    address = current_user.address
    begin
      if current_user.customer_id.nil?
        customer = Stripe::Customer.create(
          :email => params[:stripeEmail],
          :source  => params[:stripeToken],
          name: 'Jenny Rosen',
          address: {
            line1: address[:line1],
            postal_code: address[:postal_code],
            city: address[:city],
            state: address[:state],
            country: address[:country],
          }
         )
        current_user.update(:customer_id => customer.id)
      else
        customer = Stripe::Customer.new current_user.customer_id
      end

      charge = Stripe::Charge.create( 
        :customer    => customer.id, 
        :amount      => @plant.price, 
        :description => 'Rails Stripe customer', 
        :currency    => 'inr' 
      )

      redirect_to root_path
      rescue Stripe::CardError => e
        flash[:error] = e.message
        redirect_to plant_path
      end
    # end
  end

  def get_plant
    @plant = Plant.find(params[:id])
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
	before_action :authenticate_user! , only: [:show]
	def index
		@plants = Plant.all
	end

	def new
		@plant = Plant.new
	end
	
	def create
		@plant = Plant.new(name: params["plant"]["name"], price: params["plant"]["price"], avatar: params["plant"]["avatar"])
		if @plant.save
			redirect_to plants_path
		else
			render 'new'
		end
	end

	def show
		@plant = Plant.find(params[:id])
	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    @user = User.new(sign_up)
    if @user.save
      sign_in(resource)
      redirect_to root_path
      # UserMailer.welcome(@user).deliver_later
    end
  end

  private
  def sign_up
    params.require(:user).permit(:name, :email, :password, :password_confirmation, address:  [:id,:_destroy,:line1, :postal_code,:city,:country,:state])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/charges/.new.html.erb
<form action="https://www.example.com/payment/success/" method="POST"> // Replace this with your website's success callback URL
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="YOUR_KEY_ID" // Enter the Key ID generated from the Dashboard
    data-amount="50000" // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
    data-currency="INR"
    data-order_id="order_CgmcjRh9ti2lP7"//This is a sample Order ID. Pass the `id` obtained in the response of the previous step.
    data-buttontext="Pay with Razorpay"
    data-name="Acme Corp"
    data-description="Test transaction"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name="Gaurav Kumar"
    data-prefill.email="gaurav.kumar@example.com"
    data-prefill.contact="9999999999"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>

app/views/charges/create.js.erb
Thanks you paid

app/views/charges/new.html.erb
<!-- <script src="https://js.stripe.com/v2/"></script> -->
<%= form_tag checkout_payment_plant_path, method: :post do %>
  
  Grand Total : <%= @plant.price %> $
  <%#= hidden_field_tag :stripe_plan_id, @plan.stripe_plan_id %>
  <!-- <script class="stripe-button" 
             data-amount="<%#= @plant.price %>" 
             data-currency="usd" 
             data-email="<%#= current_user.email %>" 
             data-key="<%#= "pk_test_YC94Pic1v7jCyzBhi0PX8rLw00cNFJAq3s" %>" 
             src="https://checkout.stripe.com/checkout.js">
  </script> -->
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
      data-email="<%= current_user.email %>"
      data-description="A month's subscription"
      data-amount="<%= @plant.price %>"
      data-name="Ankit"
      data-locale="auto">
</script>
<% end %>

app/views/layouts/_footer.html.erb
		<!-- footer -->
	<footer class="text-center py-4">
		<div class="container py-xl-5 py-4">
			<h3 class="text-da let mb-3">We Provide Best Services</h3>
			<p class="footer-para mx-auto">Natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam
				doloremque laudantium, totam rem aperiam</p>
			<!-- logo -->
			<h2 class="logo2 text-center mt-3">
				<a href="index.html">
					Plants<i class="fa fa-pagelines" aria-hidden="true"></i>
				</a>
			</h2>
			<!-- //logo -->
			<!-- address -->
			<div class="contact-left-footer mt-4">
				<h6 class="text-da let mb-3">Sed do eiusmod tempor incididunt ut labore et dolore</h6>
				<ul>
					<li>
						<p>
							<i class="fa fa-map-marker mr-2"></i>Siddharth nagar satna, INDIA
						</p>
					</li>
					<li class="mx-4">
						<p>
							<i class="fa fa-phone mr-2"></i>8602851985.
						</p>
					</li>
					<li>
						<p class="text-wh">
							<i class="fa fa-envelope-open mr-2"></i>
							<a href="mailto:info@example.com">nurseryinthecity@gmail.com</a>
						</p>
					</li>
				</ul>
			</div>
			<!-- //address -->
			<!-- social icons -->
			<div class="footercopy-social mt-4">
				<ul>
					<li>
						<a href="#">
							<span class="fa fa-facebook-f"></span>
						</a>
					</li>
					<li class="mx-2">
						<a href="#">
							<span class="fa fa-twitter"></span>
						</a>
					</li>
					<li>
						<a href="#">
							<span class="fa fa-rss"></span>
						</a>
					</li>
					<li class="ml-2">
						<a href="#">
							<span class="fa fa-vk"></span>
						</a>
					</li>
				</ul>
			</div>
			<!-- //social icons -->
			<!-- copyright -->
			<div class="w3l-copy text-center mt-5">
				<p class="text-da">© 2020 Plants. All rights reserved | Design by
					<a href="http://w3layouts.com/">Vineet kumar Chaturvedi</a>
				</p>
			</div>
			<!-- //copyright -->
		</div>
	</footer>
	<!-- //footer -->

app/views/layouts/_header.html.erb
<header class="header-style fixed-top">
	<div class="container">
		<div class="header d-lg-flex justify-content-between align-items-center">
			<!-- logo -->
			<h1 class="logo text-center">
				<a href="index.html">Plants<i class="fa fa-pagelines" aria-hidden="true"></i>
				</a>
			</h1>
			<div class="nav_w3ls">
				<nav>
					<label for="drop" class="toggle toogle-2">Menu</label>
					<input type="checkbox" id="drop" />
					<ul class="menu">
						<li class="active ml-0"><a href="/">Home</a></li>
						<!-- <li><a href="#about">About Us</a></li> -->
						<li><%= link_to "About Us", welcome_about_us_path %></li>
						<!-- <li><a href="#services">Services</a></li> -->
						<li><%= link_to "services",  welcome_services_path %></li>
						<!-- <li><a href="#blog">Blog</a></li> -->
						<li><%= link_to "blog",  welcome_blog_path %></li>
						<!-- <li><a href="#gallery">Gallery</a></li> -->
						<li><%= link_to "gallery",  plants_path %></li>
						<!-- <li class="mr-0"><a href="#contact">Contact Us</a></li> -->
						<li><%= link_to "contact us",  welcome_contact_us_path %></li>
						<% if current_user.present? %>
			      	<li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
			      <% else%>
			      <li> <%= link_to "Sign in", new_user_session_path %></li>
			     <% end %>
					</ul>
				</nav>
			</div>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NurseryInTheCity</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/plants/index.html.erb
<!-- <table border=""> -->
	<!-- <tr> -->
		<!-- <th>Name</th> -->
		<!-- <th>Price</th> -->
		<!-- <th>View</th> -->
	<!-- </tr> -->
	<%# @plants.each do |plant| %>
		<!-- <tr> -->
			<!-- <td><%#= plant.name %></td> -->
			<!-- <td><%#= plant.price %></td>	 -->
			<!-- <td><%#= link_to "Buy", plant_path(plant) %></td>> -->
		<!-- </tr> -->
	<%# end %>
<!-- </table> -->
<%#= link_to "New Plant", new_plant_path %>
<%= render 'layouts/header'%>
	<!-- gallery -->
	<section class="portfolio py-5" id="gallery">
		<div class="container py-xl-5 py-lg-3">
			<h3 class="w3ls-title text-center font-weight-bold mb-5">Our <span class="font-weight-light">Plants</span></h3>
			<div class="row pt-4">
				<% @plants.each do |plant| %>
					<div class="col-md-3 gal-grid-wthree">
						<div class="gallery-demo">
							<a href="/plants/<%=plant.id%>">
								<h5 align="center"><%=plant.name%></h5>
								<% if plant.avatar_file_name.nil? %>
									<img src="/assets/g1.jpg" alt=" " class="img-fluid" />
								<% else %>
									<%= image_tag plant.avatar.url(:medium) %>
								<% end %>
								<h5 align="center">Price: ₹<em><%= plant.price %></em></h5>
							</a>
						</div>

					</div>
				<% end %>
				<!-- <div class="col-md-3 gal-grid-wthree my-md-0 my-4">
					<div class="gallery-demo">
						<a href="#gal2">
							<img src="/assets/g2.jpg" alt=" " class="img-fluid" />
						</a>
					</div>
				</div>
				<div class="col-md-3 gal-grid-wthree">
					<div class="gallery-demo">
						<a href="#gal3">
							<img src="/assets/g3.jpg" alt=" " class="img-fluid" />
						</a>
					</div>
				</div>
				<div class="col-md-3 gal-grid-wthree mt-md-0 mt-4">
					<div class="gallery-demo">
						<a href="#gal4">
							<img src="/assets/g4.jpg" alt=" " class="img-fluid" />
						</a>
					</div>
				</div> -->
			</div>
		<!-- 	<div class="row mt-4">
				<div class="col-md-3 gal-grid-wthree">
					<div class="gallery-demo">
						<a href="#gal5">
							<img src="/assets/g5.jpg" alt=" " class="img-fluid" />
						</a>
					</div>
				</div>
				<div class="col-md-3 gal-grid-wthree my-md-0 my-4">
					<div class="gallery-demo">
						<a href="#gal6">
							<img src="/assets/g6.jpg" alt=" " class="img-fluid" />
						</a>
					</div>
				</div>
				<div class="col-md-3 gal-grid-wthree">
					<div class="gallery-demo">
						<a href="#gal7">
							<img src="/assets/g7.jpg" alt=" " class="img-fluid" />
						</a>
					</div>
				</div>
				<div class="col-md-3 gal-grid-wthree mt-md-0 mt-4">
					<div class="gallery-demo">
						<a href="#gal8">
							<img src="/assets/g8.jpg" alt=" " class="img-fluid" />
						</a>
					</div>
				</div>
			</div> -->
		</div>
	</section>
	<!-- gallery model-->
	<%= render 'layouts/footer' %>

app/views/plants/new.html.erb
<%= form_for @plant do |f| %>
	Name: <%= f.text_field :name %> <br>
	Price: <%= f.text_field :price %> <br>
	Image: <%= f.file_field :avatar %><br>
	<%= f.submit "submit"  %>
<% end %>

app/views/plants/show.html.erb
<!-- Name: <%#= @plant.name %> <br> -->
<!-- Price: <%#= @plant.price %> -->
<!-- <button> Purchase</button> -->
<%= render 'layouts/header' %>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

  <head>
    

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">

  </head>

	
	<div class="container">
		<div class="card">
			<div class="container-fliud">
				<div class="wrapper row">
					<div class="preview col-md-6">
						
						<div class="preview-pic tab-content">
              <div class="tab-pane active" id="pic-1"><%= image_tag @plant.avatar.url(:medium) %></div>
						  <!-- <div class="tab-pane active" id="pic-1"><img src="http://placekitten.com/400/252" /></div> -->
<!-- 						  <div class="tab-pane" id="pic-2"><img src="http://placekitten.com/400/252" /></div>
						  <div class="tab-pane" id="pic-3"><img src="http://placekitten.com/400/252" /></div>
						  <div class="tab-pane" id="pic-4"><img src="http://placekitten.com/400/252" /></div>
						  <div class="tab-pane" id="pic-5"><img src="http://placekitten.com/400/252" /></div> -->
						</div>
						<ul class="preview-thumbnail nav nav-tabs">
						<!--   <li class="active"><a data-target="#pic-1" data-toggle="tab"><img src="http://placekitten.com/200/126" /></a></li>
						  <li><a data-target="#pic-2" data-toggle="tab"><img src="http://placekitten.com/200/126" /></a></li>
						  <li><a data-target="#pic-3" data-toggle="tab"><img src="http://placekitten.com/200/126" /></a></li>
						  <li><a data-target="#pic-4" data-toggle="tab"><img src="http://placekitten.com/200/126" /></a></li>
						  <li><a data-target="#pic-5" data-toggle="tab"><img src="http://placekitten.com/200/126" /></a></li> -->
						</ul>
						
					</div>
					<div class="details col-md-6">
						<h3 class="product-title"><%= @plant.name %></h3>
						<div class="rating">
							<div class="stars">
								<span class="fa fa-star checked"></span>
								<span class="fa fa-star checked"></span>
								<span class="fa fa-star checked"></span>
								<span class="fa fa-star checked"></span>
								<span class="fa fa-star"></span>
							</div>
							<span class="review-no">41 reviews</span>
						</div>
						<p class="product-description"><%= @plant.detail %></p>
						<h4 class="price">current price: <span>₹<%= @plant.price %></span></h4>
						<p class="vote"><strong>91%</strong> of buyers enjoyed this product! <strong>(87 votes)</strong></p>
						<h5 class="sizes">sizes:
							<span class="size" data-toggle="tooltip" title="small">s</span>
							<span class="size" data-toggle="tooltip" title="medium">m</span>
							<span class="size" data-toggle="tooltip" title="large">l</span>
							<span class="size" data-toggle="tooltip" title="xtra large">xl</span>
						</h5>
						<div class="action">
							<!-- <button class="add-to-cart btn btn-default" type="button">Buy</button> -->
              <%= link_to "Buy", plant_path(@plant), class: "add-to-cart btn btn-default" %>
							<!-- <button class="add-to-cart btn btn-default" type="button">add to cart</button>
							<button class="like btn btn-default" type="button"><span class="fa fa-heart"></span></button> -->
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
<%= render 'layouts/footer' %>
<style type="text/css">
	
/*****************globals*************/

img {
  max-width: 100%; }

.preview {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
  -webkit-flex-direction: column;
      -ms-flex-direction: column;
          flex-direction: column; }
  @media screen and (max-width: 996px) {
    .preview {
      margin-bottom: 20px; } }

.preview-pic {
  -webkit-box-flex: 1;
  -webkit-flex-grow: 1;
      -ms-flex-positive: 1;
          flex-grow: 1; }

.preview-thumbnail.nav-tabs {
  border: none;
  margin-top: 15px; }
  .preview-thumbnail.nav-tabs li {
    width: 18%;
    margin-right: 2.5%; }
    .preview-thumbnail.nav-tabs li img {
      max-width: 100%;
      display: block; }
    .preview-thumbnail.nav-tabs li a {
      padding: 0;
      margin: 0; }
    .preview-thumbnail.nav-tabs li:last-of-type {
      margin-right: 0; }

.tab-content {
  overflow: hidden; }
  .tab-content img {
    width: 100%;
    -webkit-animation-name: opacity;
            animation-name: opacity;
    -webkit-animation-duration: .3s;
            animation-duration: .3s; }

.card {
  margin-top: 50px;
  background: #eee;
  padding: 3em;
  line-height: 1.5em; }

@media screen and (min-width: 997px) {
  .wrapper {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex; } }

.details {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
  -webkit-flex-direction: column;
      -ms-flex-direction: column;
          flex-direction: column; }

.colors {
  -webkit-box-flex: 1;
  -webkit-flex-grow: 1;
      -ms-flex-positive: 1;
          flex-grow: 1; }

.product-title, .price, .sizes, .colors {
  text-transform: UPPERCASE;
  font-weight: bold; }

.checked, .price span {
  color: #ff9f1a; }

.product-title, .rating, .product-description, .price, .vote, .sizes {
  margin-bottom: 15px; }

.product-title {
  margin-top: 0; }

.size {
  margin-right: 10px; }
  .size:first-of-type {
    margin-left: 40px; }

.color {
  display: inline-block;
  vertical-align: middle;
  margin-right: 10px;
  height: 2em;
  width: 2em;
  border-radius: 2px; }
  .color:first-of-type {
    margin-left: 20px; }

.add-to-cart, .like {
  background: #ff9f1a;
  padding: 1.2em 1.5em;
  border: none;
  text-transform: UPPERCASE;
  font-weight: bold;
  color: #fff;
  -webkit-transition: background .3s ease;
          transition: background .3s ease; }
  .add-to-cart:hover, .like:hover {
    background: #b36800;
    color: #fff; }

.not-available {
  text-align: center;
  line-height: 2em; }
  .not-available:before {
    font-family: fontawesome;
    content: "\f00d";
    color: #fff; }

.orange {
  background: #ff9f1a; }

.green {
  background: #85ad00; }

.blue {
  background: #0076ad; }

.tooltip-inner {
  padding: 1.3em; }

@-webkit-keyframes opacity {
  0% {
    opacity: 0;
    -webkit-transform: scale(3);
            transform: scale(3); }
  100% {
    opacity: 1;
    -webkit-transform: scale(1);
            transform: scale(1); } }

@keyframes opacity {
  0% {
    opacity: 0;
    -webkit-transform: scale(3);
            transform: scale(3); }
  100% {
    opacity: 1;
    -webkit-transform: scale(1);
            transform: scale(1); } }

/*# sourceMappingURL=style.css.map */
</style>

app/views/welcome/about_us.html.erb
  # about
<%= render 'layouts/header'%>
<section class="about" id="about">
	<div class="container">
		<div class="row">
			<div class="col-lg-4 about-left-w3pvt offset-lg-1">
				<div class="main-img">
					<img src="/assets/ab.jpg" alt="" class="img-fluid pos-aboimg">
					<img src="/assets/ab2.jpg" alt="" class="img-fluid pos-aboimg2">
				</div>
			</div>
			<div class="col-lg-6 about-right offset-lg-1">
				<h4 class="sub-tittle-w3layouts let">About Us</h4>
				<h3 class="tittle-w3layouts text-uppercase pr-lg-5 mt-2">"only plants can save earth"
				</h3>
				<p class="mt-4 mb-5">In this website people can easly find plants by category and detail information will be given for planting the plants.</p>
				<ul class="author list-unstyled d-flex">
					<li><img class="img-fluid rounded-circle" src="/assets/te1.jpg" alt=""></li>
					<li class="ml-4 mt-4"><span>Admin Name</span>Comany Name</li>
				</ul>
			</div>
		</div>
	</div>
</section>
# <!-- //about -->
<%= render 'layouts/footer' %>

app/views/welcome/blog.html.erb
<%= render 'layouts/header'%>
	<!-- blog -->
	<section class="w3ls-bnrbtm py-5" id="blog">
		<div class="py-xl-5 py-lg-3">
			<div class="row no-gutters">
				<div class="col-xl-5 who-left-w3pvt offset-xl-1 pt-xl-3 pr-xl-0 pr-3">
					<h3 class="w3ls-title text-da text-center font-weight-bold mb-5 pb-lg4">Latest <span class="font-weight-light">Blog</span></h3>
					<ul class="timeline">
						<li>
							<a href="#why" class="head-text-w3">Iste natus error sit</a>
							<a href="#why" class="float-right">21 Nov, 2018</a>
							<p>Eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
								exercitation ullamco laboris.</p>
						</li>
						<li>
							<a href="#why" class="head-text-w3">Totam rem aperiam</a>
							<a href="#why" class="float-right">26 Nov, 2018</a>
							<p>Do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
								exercitation ullamco.</p>
						</li>
						<li>
							<a href="#why" class="head-text-w3">Eaque ipsa quae</a>
							<a href="#why" class="float-right">30 Nov, 2018</a>
							<p>Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.</p>
						</li>
					</ul>
				</div>
				<div class="col-xl-6 mt-xl-0 mt-md-5 mt-4 text-xl-right text-center">
					<img class="img-fluid rounded" src="/assets/blog.jpg" alt="">
				</div>
			</div>
		</div>
	</section>
	<!-- //blog -->
	<%= render 'layouts/footer' %>

app/views/welcome/contact_us.html.erb
<%= render 'layouts/header'%>
	<!-- contact -->
	<section class="contact py-5" id="contact">
		<div class="container py-xl-5 py-lg-3">
			<h3 class="w3ls-title text-wh text-center font-weight-bold mb-5">Contact <span class="font-weight-light">Us</span></h3>
			<div class="row contact-form">
				<div class="offset-lg-2"></div>
				<div class="col-lg-8 wthree-form-left">
					<!-- contact form grid -->
					<fieldset class="contact-top1" data-blast="borderColor">
						<legend class="text-wh let text-capitalize">send us a note</legend>
						<form action="#" method="post" class="f-color">
							<div class="form-group">
								<label for="contactusername">Name</label>
								<input type="text" class="form-control" name="name" id="contactusername" required placeholder="Enter your name">
							</div>
							<div class="form-group">
								<label for="contactemail">Email</label>
								<input type="email" class="form-control" name="email" id="contactemail" required placeholder="Enter your Email">
							</div>
							<div class="form-group">
								<label for="contactcomment">Your Message</label>
								<textarea class="form-control" rows="5" name="message" id="contactcomment" required placeholder="your message"></textarea>
							</div>
							<button type="submit" class="btn btn-block" data-blast="bgColor">Send</button>
						</form>
					</fieldset>
					<!--  //contact form grid ends here -->
				</div>
				<div class="offset-lg-2"></div>
			</div>
			<!-- contact address -->
			<div class="row address bg-li">
				<div class="col-lg-4 address-grid">
					<div class="row address-info">
						<div class="col-md-3 col-4 address-left text-lg-center text-sm-right text-center">
							<i class="fa fa-envelope"></i>
						</div>
						<div class="col-md-9 col-8 address-right">
							<p>
								<a href="mailto:example@email.com"> nurseryinthecity@gmail.com</a>
							</p>
							<p>
								<a href="mailto:example@email.com"> hiivineet@gmail.com</a>
							</p>
						</div>
					</div>
				</div>
				<div class="col-lg-4 address-grid my-lg-0 my-4">
					<div class="row address-info">
						<div class="col-md-3 col-4 address-left text-lg-center text-sm-right text-center">
							<i class="fa fa-phone"></i>
						</div>
						<div class="col-md-9 col-8 address-right">
							<p>918602851985</p>
							<p>916263717585</p>
						</div>
					</div>
				</div>
				<div class="col-lg-4 address-grid">
					<div class="row address-info">
						<div class="col-md-3 col-4 address-left text-lg-center text-sm-right text-center">
							<i class="fa fa-map"></i>
						</div>
						<div class="col-md-9 col-8 address-right">
							<p> MIG 52 bandhavgadh colony</p>
							<p> Satna Madhyapradesh ,INDIA</p>
						</div>
					</div>
				</div>
			</div>
			<!-- //contact address -->
		</div>
	</section>
	<!-- //contact -->
	<%= render 'layouts/footer' %>